// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ZALrdj46VaYn1jovci5YWpbbXqhlvas',
    appId: '1:642749402399:web:9121eb90f9b359a848742a',
    messagingSenderId: '642749402399',
    projectId: 'notification-dd3bb',
    authDomain: 'notification-dd3bb.firebaseapp.com',
    storageBucket: 'notification-dd3bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyomBAaGu26MOv8YuiKyGhk_ikOP0zy0M',
    appId: '1:642749402399:android:4771ea9559a50ceb48742a',
    messagingSenderId: '642749402399',
    projectId: 'notification-dd3bb',
    storageBucket: 'notification-dd3bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOITGu5HRJ3hezjUMJNYeNST3_wVfAqi4',
    appId: '1:642749402399:ios:a1c0a99694605a3848742a',
    messagingSenderId: '642749402399',
    projectId: 'notification-dd3bb',
    storageBucket: 'notification-dd3bb.appspot.com',
    iosClientId: '642749402399-hc9092efk3url5s970bnp6qjlh8pjkbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOITGu5HRJ3hezjUMJNYeNST3_wVfAqi4',
    appId: '1:642749402399:ios:a1c0a99694605a3848742a',
    messagingSenderId: '642749402399',
    projectId: 'notification-dd3bb',
    storageBucket: 'notification-dd3bb.appspot.com',
    iosClientId: '642749402399-hc9092efk3url5s970bnp6qjlh8pjkbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationTest',
  );
}
